# Generated by Django 4.0 on 2024-02-24 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directmessages', '0003_conversation_active_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='archived_by',
            field=models.ManyToManyField(blank=True, related_name='archived_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
