# Generated by Django 4.2.2 on 2023-10-24 16:14

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_folllowing_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profilename',
            field=models.CharField(default='user', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2023, 10, 24, 16, 13, 43, 324160, tzinfo=datetime.timezone.utc)),
        ),
    ]
