# Generated by Django 4.2.2 on 2023-10-24 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_pfp_user_profilename_alter_post_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2023, 10, 24, 16, 18, 39, 427750, tzinfo=datetime.timezone.utc)),
        ),
    ]
