# Generated by Django 4.2.2 on 2023-10-25 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_timestamp_alter_user_folllowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='folllowing',
            new_name='following',
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2023, 10, 25, 16, 10, 28, 578321, tzinfo=datetime.timezone.utc)),
        ),
    ]
