# Generated by Django 4.2.2 on 2024-01-07 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_rename_folllowing_user_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2024, 1, 7, 15, 17, 43, 923247, tzinfo=datetime.timezone.utc)),
        ),
    ]
