# Generated by Django 4.2.2 on 2024-01-11 22:21

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='transmissions',
            field=models.ManyToManyField(blank=True, related_name='transmitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2024, 1, 11, 22, 21, 26, 506834, tzinfo=datetime.timezone.utc)),
        ),
    ]
