# Generated by Django 4.2.2 on 2024-01-22 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='transmissions',
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ManyToManyField(related_name='transmissions', to='network.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
