# Generated by Django 4.2.2 on 2024-01-22 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_post_transmissions_transmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transmission',
            name='post',
        ),
        migrations.AddField(
            model_name='transmission',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='network.post'),
        ),
    ]
