# Generated by Django 4.2.2 on 2024-01-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_user_date_joined_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='target', to='network.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='reply',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
