# Generated by Django 4.2.2 on 2024-01-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_remove_post_replies_post_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='replies',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='network.post'),
        ),
    ]
