# Generated by Django 4.2.2 on 2024-01-28 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_mention_origin_mention_post_mention_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
