# Generated by Django 4.2.2 on 2024-01-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_notification_delete_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
