# Generated by Django 4.2.2 on 2024-02-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code',
            field=models.IntegerField(default=-1),
        ),
    ]
