# Generated by Django 4.2.2 on 2024-02-01 16:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_code_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 16, 35, 58, 655805, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='code',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code', to=settings.AUTH_USER_MODEL),
        ),
    ]
