# Generated by Django 4.2.2 on 2024-02-01 16:26

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_alter_code_expiration_date_alter_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='expiration_date',
            field=models.DateTimeField(default=network.models.get_expiration_date),
        ),
    ]
