# Generated by Django 4.2.2 on 2024-02-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_alter_code_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
