# Generated by Django 4.2.2 on 2024-02-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0028_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(default=None),
        ),
    ]
