# Generated by Django 4.2.2 on 2024-02-03 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0029_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
